// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Item struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ParsingResult struct {
	ID          int64
	UrlID       int64
	DateRun     time.Time
	StatusCode  int64
	RawBody     sql.NullString
	TargetField sql.NullFloat64
}

type Url struct {
	ID        int64
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
}
