// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: urls.sql

package database

import (
	"context"
)

const addURL = `-- name: AddURL :one
INSERT INTO urls(url, tracked_element)
     VALUES (?, ?)
  RETURNING id, url, created_at, updated_at, tracked_element
`

type AddURLParams struct {
	Url            string
	TrackedElement string
}

func (q *Queries) AddURL(ctx context.Context, arg AddURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, addURL, arg.Url, arg.TrackedElement)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackedElement,
	)
	return i, err
}
