-- +goose Up
CREATE TABLE urls (
  id INTEGER PRIMARY KEY NOT NULL,
  url TEXT UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  tracked_element TEXT NOT NULL
);

-- +goose Down
DROP TABLE urls;
